name: Release for tags
on:
  push:
  pull_request:
  create:
    tags:
      - 'v*'

jobs:
  create-artifacts:
    name: Create artifacts
    runs-on: ubuntu-20.04
    env:
      release: ${{ github.event_name == 'create' && startsWith(github.ref, 'v')}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install wine
        run: sudo apt-get update && sudo apt-get install wine && dpkg --add-architecture i386 && apt-get update && apt-get install wine32
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: NPM install
        run: npm install --dev
      - name: Prepare
        run: npm run build
      - name: Build Electron
        run: npm run install-electron && npm run package-electron
      - name: Build Node
        run: npm run install-node && npm run package-node
      - name: Package node-linux
        run: zip -j dist/node/ud3-node-linux.zip dist/node/ud3-node node_modules/@serialport/bindings/build/Release/bindings.node
      - name: Get Windows serialport bindings
        run: (cd node_modules/@serialport/bindings && npx prebuild-install --tag-prefix @serialport/bindings@ -r node --platform win32)
      - name: Package node-windows
        run: zip -j dist/node/ud3-node-win.zip dist/node/ud3-node.exe node_modules/@serialport/bindings/build/Release/bindings.node
      - name: Upload electron-linux
        uses: actions/upload-artifact@v2
        with:
          path: dist/electron/teslaterm-linux.zip
          name: teslaterm-linux.zip
      - name: Upload electron-win
        uses: actions/upload-artifact@v2
        with:
          path: dist/electron/teslaterm-win.zip
          name: teslaterm-windows.zip
      - name: Upload node-linux
        uses: actions/upload-artifact@v2
        with:
          path: dist/node/ud3-node-linux.zip
          name: ud3-node-linux.zip
      - name: Upload node-win
        uses: actions/upload-artifact@v2
        with:
          path: dist/node/ud3-node-win.zip
          name: ud3-node-win.zip
      - name: Create release
        if: env.release == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Release electron-linux
        if: env.release == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/electron/teslaterm-linux.zip
          asset_name: teslaterm-linux.zip
          asset_content_type: application/zip
      - name: Release electron-windows
        if: env.release == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/electron/teslaterm-win.zip
          asset_name: teslaterm-windows.zip
          asset_content_type: application/zip
      - name: Release node-linux
        if: env.release == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/node/ud3-node-linux.zip
          asset_name: ud3-node-linux.zip
          asset_content_type: application/zip
      - name: Release node-windows
        if: env.release == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/node/ud3-node-win.zip
          asset_name: ud3-node-windows.zip
          asset_content_type: application/zip
